<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Magasinier</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/album/">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <meta name="theme-color" content="#712cf9">
</head>

<header>
<nav class="navbar navbar-expand-lg bg-body-tertiary" id="nav">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">SOTULUB Bizerte</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"><i class="bi bi-house"></i> Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><i class="bi bi-align-bottom"></i> Presentation de la societe </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><i class="bi bi-check-circle-fill"></i> Taches effectue</a>
        </li>
      </ul>
      <span class="navbar-text">
     <a href="deconnexion.php"><i class="bi bi-door-closed"></i> Deconnexion</a>
      </span>
    </div>
  </div>
</nav>
</header>
<body>


<div class="container text-center" id="form1">
  <div class="row">
    <div class="col">
    <form action="update.php" method="POST">
    <input type="hidden" name="id" value='<?=isset($_GET['id']) ? $_GET['id'] : ''?>'>
    <?php if(array_key_exists('msg',$_GET)):?> 
      <div class="alert alert-success" role="alert">
      <?=$_GET['msg']?>
</div>
  <?php endif; ?>
  <input type="hidden" class="form-control"  id="#" name="id" value="<?=$produits['id_produit'] ?>">
  <div class="mb-3">
    <label for="codearticle" class="form-label" >Code Article</label>
    <input type="text" class="form-control"  id="#" name="code_article" value="<?=$produits['code_article'] ?>">
  </div>
  <div class="mb-3">
    <label for="Emplacement" class="form-label">Emplacement</label>
    <input type="text" class="form-control"  id="#" name="Emplacement" value="<?=$produits['Emplacement'] ?>">
  </div>
   
  <div class="mb-3">
    <label for="Designation" class="form-label">Designation</label>
    <input type="text" class="form-control"  id="#" name="Designation" value="<?=$produits['designation'] ?>">
  </div>
   
  <div class="mb-3">
    <label for="Code magasin" class="form-label">Code Magasin</label>
    <input type="text" class="form-control"  id="#" name="code_mag" value="<?=$produits['code_mag'] ?>">
  </div>
  
  <div class="mb-3">
    <label for="prix" class="form-label">Prix d'ahcat</label>
    <input type="text" class="form-control"  id="#" name="prix" value="<?=$produits['prix'] ?>">
  </div>

  <div class="mb-3">
    <label for="date_entree" class="form-label">Date entrée</label>
    <input type="date" class="form-control"  id="#" name="date_entree" value="<?=$produits['date_entree'] ?>">
  </div>

  <div class="mb-3">
    <label for="quantite" class="form-label">Quantite</label>
    <input type="number" class="form-control"  id="#" name="quantite" value="<?=$produits['quantité'] ?>">
  </div>


  <button type="submit" class="btn btn-success" name="update"><i class="bi bi-cloud-upload"></i> Mise à jour Produit</button>
  
</form>
    </div>
    <div class="col">
      <img src="media/Admin5.PNG" alt="Bienvenue admin" id="img">
    </div>
  </div>
</div>
    
</body>

<style>
   @import url('https://fonts.googleapis.com/css?family=Advent+Pro|Dancing+Script&display=swap');
      #nav{
        background-color: #87bba2;
    }
    #form1 {
        margin-top:20px;
        -webkit-box-shadow: -3px 6px 15px -2px #000000; 
        box-shadow: -3px 6px 15px -2px #000000;
        padding: 0.8em;
        
    }
    
    #img {
        height:110%;
        width:70%;
    }
    a {
        text-decoration:none;
    }

    #add{
        margin-top:30px;
        margin-left:40%
    } 
</style>